### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by fibigerg** [toranb/ember-data-django-rest-adapter#80]
Hello

I am responding to this post https://github.com/toranb/ember-data-django-rest-adapter/issues/58

Did you make any progress on this issue? I think we really need a pagination for production usage of Django REST Adapter + Ember.

I tried to look into code by myself, but i don't think i have enough knowledge of Ember to implement it, yet.

Thank you for answer.

Gary

**Comment by Ghostavio** [comment]
So, was this fixed on the new ember-cli addon?

**Comment by benkonrath** [comment]
We're still working on it.

https://github.com/dustinfarris/ember-django-adapter/pull/45
